package DAO;

// Generated 27 mai 2014 15:32:27 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Intervenant generated by hbm2java
 */
public class Intervenant implements java.io.Serializable {

	private Integer idIntervenant;
	private String nom;
	private String prenom;
	private String portable;
	private String email;
	private Set agendas = new HashSet(0);

	public Intervenant() {
	}

	public Intervenant(String nom, String prenom, String portable) {
		this.nom = nom;
		this.prenom = prenom;
		this.portable = portable;
	}

	public Intervenant(String nom, String prenom, String portable,
			String email, Set agendas) {
		this.nom = nom;
		this.prenom = prenom;
		this.portable = portable;
		this.email = email;
		this.agendas = agendas;
	}

	public Integer getIdIntervenant() {
		return this.idIntervenant;
	}

	public void setIdIntervenant(Integer idIntervenant) {
		this.idIntervenant = idIntervenant;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getPortable() {
		return this.portable;
	}

	public void setPortable(String portable) {
		this.portable = portable;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getAgendas() {
		return this.agendas;
	}

	public void setAgendas(Set agendas) {
		this.agendas = agendas;
	}

}
