package DAO;

// Generated 27 mai 2014 15:32:27 by Hibernate Tools 4.0.0

/**
 * Piecejoin generated by hbm2java
 */
public class Piecejoin implements java.io.Serializable {

	private Integer idPiecejoin;
	private Prospect prospect;
	private Agenda agenda;
	private String denomination;
	private Boolean piecejoinprospect;
	private Boolean piecejoinevenement;
	private byte[] pj;
	private String type;

	public Piecejoin() {
	}

	public Piecejoin(String denomination, byte[] pj, String type) {
		this.denomination = denomination;
		this.pj = pj;
		this.type = type;
	}

	public Piecejoin(Prospect prospect, Agenda agenda, String denomination,
			Boolean piecejoinprospect, Boolean piecejoinevenement, byte[] pj,
			String type) {
		this.prospect = prospect;
		this.agenda = agenda;
		this.denomination = denomination;
		this.piecejoinprospect = piecejoinprospect;
		this.piecejoinevenement = piecejoinevenement;
		this.pj = pj;
		this.type = type;
	}

	public Integer getIdPiecejoin() {
		return this.idPiecejoin;
	}

	public void setIdPiecejoin(Integer idPiecejoin) {
		this.idPiecejoin = idPiecejoin;
	}

	public Prospect getProspect() {
		return this.prospect;
	}

	public void setProspect(Prospect prospect) {
		this.prospect = prospect;
	}

	public Agenda getAgenda() {
		return this.agenda;
	}

	public void setAgenda(Agenda agenda) {
		this.agenda = agenda;
	}

	public String getDenomination() {
		return this.denomination;
	}

	public void setDenomination(String denomination) {
		this.denomination = denomination;
	}

	public Boolean getPiecejoinprospect() {
		return this.piecejoinprospect;
	}

	public void setPiecejoinprospect(Boolean piecejoinprospect) {
		this.piecejoinprospect = piecejoinprospect;
	}

	public Boolean getPiecejoinevenement() {
		return this.piecejoinevenement;
	}

	public void setPiecejoinevenement(Boolean piecejoinevenement) {
		this.piecejoinevenement = piecejoinevenement;
	}

	public byte[] getPj() {
		return this.pj;
	}

	public void setPj(byte[] pj) {
		this.pj = pj;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
