package DAO;

// Generated 27 mai 2014 15:32:27 by Hibernate Tools 4.0.0

/**
 * Representant generated by hbm2java
 */
public class Representant implements java.io.Serializable {

	private Integer idRepresantant;
	private Prospect prospect;
	private String nom;
	private String prenom;
	private String telephone;
	private String ville;

	public Representant() {
	}

	public Representant(String nom, String prenom, String telephone,
			String ville) {
		this.nom = nom;
		this.prenom = prenom;
		this.telephone = telephone;
		this.ville = ville;
	}

	public Representant(Prospect prospect, String nom, String prenom,
			String telephone, String ville) {
		this.prospect = prospect;
		this.nom = nom;
		this.prenom = prenom;
		this.telephone = telephone;
		this.ville = ville;
	}

	public Integer getIdRepresantant() {
		return this.idRepresantant;
	}

	public void setIdRepresantant(Integer idRepresantant) {
		this.idRepresantant = idRepresantant;
	}

	public Prospect getProspect() {
		return this.prospect;
	}

	public void setProspect(Prospect prospect) {
		this.prospect = prospect;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

}
