package DAO;

// Generated 27 mai 2014 15:32:27 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Statut generated by hbm2java
 */
public class Statut implements java.io.Serializable {

	private Integer idStatut;
	private String denomination;
	private String libelle;
	private Boolean statutprospect;
	private Boolean statutevenement;
	private Set prospects = new HashSet(0);
	private Set agendas = new HashSet(0);

	public Statut() {
	}

	public Statut(String denomination, String libelle) {
		this.denomination = denomination;
		this.libelle = libelle;
	}

	public Statut(String denomination, String libelle, Boolean statutprospect,
			Boolean statutevenement, Set prospects, Set agendas) {
		this.denomination = denomination;
		this.libelle = libelle;
		this.statutprospect = statutprospect;
		this.statutevenement = statutevenement;
		this.prospects = prospects;
		this.agendas = agendas;
	}

	public Integer getIdStatut() {
		return this.idStatut;
	}

	public void setIdStatut(Integer idStatut) {
		this.idStatut = idStatut;
	}

	public String getDenomination() {
		return this.denomination;
	}

	public void setDenomination(String denomination) {
		this.denomination = denomination;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Boolean getStatutprospect() {
		return this.statutprospect;
	}

	public void setStatutprospect(Boolean statutprospect) {
		this.statutprospect = statutprospect;
	}

	public Boolean getStatutevenement() {
		return this.statutevenement;
	}

	public void setStatutevenement(Boolean statutevenement) {
		this.statutevenement = statutevenement;
	}

	public Set getProspects() {
		return this.prospects;
	}

	public void setProspects(Set prospects) {
		this.prospects = prospects;
	}

	public Set getAgendas() {
		return this.agendas;
	}

	public void setAgendas(Set agendas) {
		this.agendas = agendas;
	}

}
