package DAO;

// Generated 27 mai 2014 15:32:27 by Hibernate Tools 4.0.0

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur implements java.io.Serializable {

	private Integer idUtilisateur;
	private String nom;
	private String motdepasse;
	private boolean admin;

	public Utilisateur() {
	}

	public Utilisateur(String nom, boolean admin) {
		this.nom = nom;
		this.admin = admin;
	}

	public Utilisateur(String nom, String motdepasse, boolean admin) {
		this.nom = nom;
		this.motdepasse = motdepasse;
		this.admin = admin;
	}

	public Integer getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(Integer idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getMotdepasse() {
		return this.motdepasse;
	}

	public void setMotdepasse(String motdepasse) {
		this.motdepasse = motdepasse;
	}

	public boolean isAdmin() {
		return this.admin;
	}

	public void setAdmin(boolean admin) {
		this.admin = admin;
	}

}
